---

- name: "Creates directory for backend"
  file:
    path: ~/backend
    state: directory

- name: copy archived file into remote server
  copy:
    src: ~/artifact.tar.gz
    dest: /home/ubuntu/backend/artifact.tar.gz
    mode: "0777"
    backup: yes

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend
    npm i
    # tar -xvzf artifact.tar.gz
    # npm install -f

- name: "Executing Node app with PM2"
  shell: |
    cd ~/backend
    pm2 stop default
    pm2 start main.js
    # pm2 start npm -- start -f
    # pm2 list

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    # sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    # pm2 save
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu